### ISSUE TITLE
Replace `emu-internal-ref refid="id"` with `emu-xref href="#id"`

### ISSUE THREAD

**Issue by bterlson** [jmdyck/es-spec-emu#10]

**Comment by bterlson** [comment]
Unless it's a title link, in which case add the title attribute to the emu-xref element.

**Comment by jmdyck** [comment]
Done!

> Unless it's a title link, in which case add the title attribute to the emu-xref element.

The HTML ES6 spec doesn't have any title links per se. (Or, any that it has are more easily handled as auto-links than as explicit links.)
