### ISSUE TITLE
Subclauses of annexes should still be annexes

### ISSUE THREAD

**Issue by bterlson** [jmdyck/es-spec-emu#2]
Presently the output has emu-clause's nested under annexes.

**Comment by jmdyck** [comment]
I think I originally had it as you suggest, and then something caused me to change it, but now I can't remember what it was. Anyhow, shouldn't be a problem to change it back.

The documentation indicates that an `<emu-annex>` without the 'normative' attribute is non-normative, which suggests that 'normativity' isn't inherited down the document-tree. So it isn't enough to mark Annex B as normative, all its sub-annexes have to be marked normative too. Is that a correct interpretation?

**Comment by bterlson** [comment]
My intention is for normativity to be inherited. Why wouldn't it be?

**Comment by jmdyck** [comment]
> My intention is for normativity to be inherited.

Great!

> Why wouldn't it be?

I wasn't saying there was a reason it _shouldn't_ be inherited, just that the documentation doesn't say it _is_ inherited.

**Comment by bterlson** [comment]
I think this can be closed?

**Comment by jmdyck** [comment]
yup.
