### ISSUE TITLE
Need aoid for emu-clauses that define abstract operations

### ISSUE THREAD

**Issue by bterlson** [jmdyck/es-spec-emu#4]
Title says it, I think?

**Comment by bterlson** [comment]
FWIW, this is blocking my effort to update the emu biblio file with the latest ES6. If it's possible to do this quickly/easily I'd appreciate it :)

**Comment by jmdyck** [comment]
Right, I had a question about that, should have put it in the conversion notes. But rather than pose the question now, I'll see if I can get the aoids in tonight.

**Comment by jmdyck** [comment]
Done! (Forgot to mention this issue# in the commit message.)
Notes:
There are 2 aoids that contain '/':

```
    aoid="ForIn/OfHeadEvaluation"
    aoid="ForIn/OfBodyEvaluation"
```

and 4 that contain spaces:

```
    aoid="ToString Applied to the Number Type"
    aoid="Abstract Relational Comparison"
    aoid="Abstract Equality Comparison"
    aoid="Strict Equality Comparison"
```

All others are just alphanumeric characters.

**Comment by jmdyck** [comment]
Also, I didn't add an aoid for ReturnIfAbrupt or IfAbruptRejectPromise, as those appear to be shorthands (macros) rather than abstract operations. I wasn't sure about Completion and NormalCompletion either. Would you like them to get an aoid anyway?

**Comment by jmdyck** [comment]
Also, there's one emu-annex with an aoid, "CreateHTML", although the ecmarkup documentation doesn't say that an emu-annex can have an aoid.

**Comment by bterlson** [comment]
Interesting examples... I guess the ones with spaces are never called from algorithm steps.

> Also, I didn't add an aoid for ReturnIfAbrupt or IfAbruptRejectPromise, as those appear to be shorthands (macros) rather than abstract operations. I wasn't sure about Completion and NormalCompletion either. Would you like them to get an aoid anyway?

Yeah I think that makes sense. Want auto-linking from algorithms (although I think I have to implement linking the form `Completion{...}`).

Will update docs to reflect that an annex can have an aoid. I guess emu-intro can as well.

**Comment by bterlson** [comment]
Looks great! Have an up-to-date biblio now, seems accurate.

**Comment by jmdyck** [comment]
> Interesting examples... I guess the ones with spaces are never called from algorithm steps.

Well, they are invoked, but not with the usual prefix-parenthesis notation. E.g.:

```
    Return the result of performing Strict Equality Comparison _x_ === _y_.
```

> > Would you like them to get an aoid anyway?
> 
> Yeah I think that makes sense. Want auto-linking from algorithms

Okay, I've added aoids for NormalCompletion, Completion, ReturnIfAbrupt, and IfAbruptRejectPromise.

> (although I think I have to implement linking the form Completion{...}).

Note that `Completion{...}` is different from `Completion(...)`. If you link the form with the braces, it would probably go to 6.2.2 "The Completion Record Specification Type", whereas the form with parens links to 6.2.2.2 "Implicit Completion Values".

> Will update docs to reflect that an annex can have an aoid. I guess emu-intro can as well.

That'd be pretty weird if it did.

**Comment by jmdyck** [comment]
One of the things I was wondering was why the 'aoid' attribute was allowed on both emu-clause and emu-alg. Was there a particular situation you had in mind where you'd want to link to an emu-alg rather than an emu-clause?

(Also, in the description for emu-alg, it says "A unique name identifying this clause", but "clause" should presumably be "algorithm" or "element".)

**Comment by jmdyck** [comment]
Anyhow, sounds like I can close this.

**Comment by bterlson** [comment]
> That'd be pretty weird if it did.

I agree but I believe emu-intro and annex inherit from emu-clause and therefore it makes sense for them to support all the same attributes.
