### ISSUE TITLE
dfn and emu phrases

### ISSUE THREAD

**Issue by bterlson** [jmdyck/es-spec-emu#5]
I notice that dfn is used heavily in your output. Which is great! But I wonder two things:
1. How can we get a dfn for Completion such that Completion{ ... } links appropriately?
2. Are dfns over-used? For example there is a dfn for "language" and some other really basic terms. Do we want those auto-linking all over the place?

**Comment by jmdyck** [comment]
> I notice that dfn is used heavily in your output.

(There's a note about them in the notes_on_conversion.)

> How can we get a dfn for Completion such that Completion{ ... } links appropriately?

Clause 6.2.2 ("The Completion Record Specification Type") begins with "The Completion type is a Record...". If we put that "Completion" in a `<dfn>`, then (in a `<dfn>`-based autolinking scheme) that would suffice to auto-link "Completion{...}" back to that section. That's easy.

The _problem_ is that clause 6.2.2.2 ("Implicit Completion Values") defines an abstract operation that is also named "Completion", and uses of that operation should properly link back to _this_ section (though they don't in the HTML ES6 spec).

To handle this, I think the auto-linking code should just have a special case for "Completion". That is,`/\bCompletion(?= *\()/` should link to 6.2.2.2, and any other `/\bCompletion\b/` should link to 6.2.2.

> Are dfns over-used? For example there is a dfn for "language" and some other really basic terms. Do we want those auto-linking all over the place?

No, that'd probably be distracting and unhelpful. And yet, we might still want that defining occurrence of "language" to be emphasized. In which case, we'd need to distinguish between a defining occurrence that causes auto-links and one that doesn't. So, to distinguish those two roles, would you like `<dfn>` vs. `<i>` (or `<em>`), or perhaps `<emu-dfn>` vs. `<dfn>`? Or, say, `<dfn link-worthy>` vs `<dfn>`?

**Comment by bterlson** [comment]
> To handle this, I think the auto-linking code should just have a special case for "Completion". That is, /\bCompletion(?= *()/  should link to 6.2.2.2, and any other  /\bCompletion\b/  should link to 6.2.2.

I don't think it's worth a special case. Both should just link to 6.2.2. We could consider tweaking the authoring conventions so this is less awkward. I don't understand the value of the abstract operation, but maybe I'm missing something...

I like `<em>` and `<dfn>`. `<dfn>` defines a term worth auto-linking to IMO.

**Comment by jmdyck** [comment]
> I don't think it's worth a special case. Both should just link to 6.2.2.

Okay, just like the HTML ES6 spec.

> I like `<em>` and `<dfn>`. `<dfn>` defines a term worth auto-linking to IMO.

Okay, so as a first step, in es-spec.emu, I've changed `<dfn>` to `<em>` for all the phrases that are _not_ worthy of auto-linking, as far as the HTML ES6 spec is concerned. (Somewhat surprisingly, this leaves only 8 `<dfn>s`!)

**Comment by bterlson** [comment]
That is surprising!

Did you do this manually or will future conversions from an html source maintain these 8 dfns?

**Comment by jmdyck** [comment]
The whole HTML -> emu pipeline is scripted, so yes, subsequent runs are maintaining those 8 dfns.

**Comment by bterlson** [comment]
woo!

**Comment by jmdyck** [comment]
`aoid="Completion"` has now moved from 6.2.2.2 to 6.2.2.

I think that resolves this issue. Please confirm.
