### ISSUE TITLE
Abrupt completion should be a dfn

### ISSUE THREAD

**Issue by bterlson** [jmdyck/es-spec-emu#6]
See this section: http://www.ecma-international.org/ecma-262/6.0/index.html#sec-completion-record-specification-type.

**Comment by bterlson** [comment]
Also need a dfn for "Completion" I think?

**Comment by jmdyck** [comment]
Yup, I've got some new `<dfn>s` in the works.

**Comment by jmdyck** [comment]
I've added `<dfn>` tags for:

```
    ECMAScript language type
    ECMAScript language value
    List
    abrupt completion
    Property Descriptor
    Data Block
    EnvironmentRecord
    Environment Record
    Realm
    %ThrowTypeError%
    Directive Prologue
    Use Strict Directive
    Module Record
    Source Text Module Record
    LocalTZA
    this time value
```

Do you still need a `<dfn>` for 'Completion', given that 6.2.2 has `aoid="Completion"`?

**Comment by bterlson** [comment]
I don't think so. In fact I am planning on adding a warning condition for an aoid and dfn of the same name as it will be unlikely to auto-link correctly...

**Comment by jmdyck** [comment]
Okay, sounds like I can close this then.
