### ISSUE TITLE
use gh-pages branch instead of master

### ISSUE THREAD

**Issue by michaelficarra** [jmdyck/es-spec-emu#8]
This will allow a preview of the HTML file in the browser via Github Pages.

**Comment by bterlson** [comment]
I agree. I am planning on starting up an official HTML repo on the tc39 GitHub soon (essentially, factor out the spec part of this repo). Want to fix a few bugs in Emu before I do so though.

**Comment by jmdyck** [comment]
Currently, the HTML file here looks pretty much the same as the [official HTML for the ES6 spec](www.ecma-international.org/ecma-262/6.0/), so there isn't much benefit in making it easily viewable.

Of course, that will change once the emu file starts to get 7th edition edits, but I expect that won't happen in this repo. So I'm inclined to close this issue with no action.

**Comment by bterlson** [comment]
Yes, I think you can close. Once ES7 edits start happening I will likely take the es-spec.emu file from this repo as the starting point. Assuming I am making edits in word, I expect it will be easy to update es-spec.emu as new tooling updates come online.
